# -------------------------------------------------------------------------------------------
#
#  Welcome to Stylizer's main configuration file.
#
#  Here you'll find of the settings and options that you can
#  customize to your server needs. Most features are customizable
#  to an extent.
#
#  For help you can visit the wiki at: https://github.com/OmegaWeaponDev/OmegaNames/wiki
#  If you have any issues, report them here: https://github.com/OmegaWeaponDev/OmegaNames/issues
#
#  Stylizer Placeholders:
#    %displayname% - Gets the players namecolour and name.
#    %message% - Gets the players chat message.
#
#
# -------------------------------------------------------------------------------------------

# If true, each of the name colours will require a specific permission
# Use the permission `stylizer.namecolour.colour.<colour>` or `stylizer.namecolour.colour.all`
# If false, use the permission `stylizer.namecolour.colours`
Per_Name_Colour_Permissions: false

# If true, each of the chat colours will require a specific permission
# Use the permission `stylizer.chatcolour.colour.<colour>` or `stylizer.chatcolour.colour.all`
# If false, use the permission `stylizer.chatcolour.colours`
Per_Chat_Colour_Permissions: false

# If true, players will retain their name colour when they login/logout
Name_Colour_Login: true

# The default namecolour players will have if they have not chosen a current name colour
Default_Name_Colour: "&e"

# The default chatcolour players will have if they have not chosen a current chat colour
Default_Chat_Colour: "&f"

# Set all the different name colours and the item that you want in the GUI
# This will accept both the normal colour codes (&4) and hex colour codes (#123456)
Name_Colour_Items:
  Dark Red:
    Colour: "#670E00"
    Item: NETHER_WART
  Red:
    Colour: "#FF0101"
    Item: RED_WOOL
  Gold:
    Colour: "#FFDC01"
    Item: GOLD_BLOCK
  Yellow:
    Colour: "#FFFB01"
    Item: YELLOW_WOOL
  Green:
    Colour: "#1FAA00"
    Item: GREEN_WOOL
  Lime:
    Colour: "#36FF09"
    Item: LIME_DYE
  Aqua:
    Colour: "#09FFEC"
    Item: LIGHT_BLUE_WOOL
  Dark Aqua:
    Colour: "#00B4A6"
    Item: CYAN_WOOL
  Dark Blue:
    Colour: "#000E86"
    Item: BLUE_WOOL
  Blue:
    Colour: "#004DFF"
    Item: BLUE_ORCHID
  Pink:
    Colour: "#FF00FF"
    Item: PINK_TULIP
  Purple:
    Colour: "#8000FF"
    Item: MAGENTA_SHULKER_BOX
  White:
    Colour: "#FFFFFF"
    Item: QUARTZ_BLOCK
  Light Gray:
    Colour: "#CBCBCB"
    Item: LIGHT_GRAY_WOOL
  Gray:
    Colour: "#818181"
    Item: STONE
  Black:
    Colour: "#000000"
    Item: BLACK_WOOL

# Set all the different chat colours and the item that you want in the GUI
# This will accept both the normal colour codes (&4) and hex colour codes (#123456)
Chat_Colour_Items:
  Dark Red:
    Colour: "#670E00"
    Item: NETHER_WART
  Red:
    Colour: "#FF0101"
    Item: RED_WOOL
  Gold:
    Colour: "#FFDC01"
    Item: GOLD_BLOCK
  Yellow:
    Colour: "#FFFB01"
    Item: YELLOW_WOOL
  Green:
    Colour: "#1FAA00"
    Item: GREEN_WOOL
  Lime:
    Colour: "#36FF09"
    Item: LIME_DYE
  Aqua:
    Colour: "#09FFEC"
    Item: LIGHT_BLUE_WOOL
  Dark Aqua:
    Colour: "#00B4A6"
    Item: CYAN_WOOL
  Dark Blue:
    Colour: "#000E86"
    Item: BLUE_WOOL
  Blue:
    Colour: "#004DFF"
    Item: BLUE_ORCHID
  Pink:
    Colour: "#FF00FF"
    Item: PINK_TULIP
  Purple:
    Colour: "#8000FF"
    Item: MAGENTA_SHULKER_BOX
  White:
    Colour: "#FFFFFF"
    Item: QUARTZ_BLOCK
  Light Gray:
    Colour: "#CBCBCB"
    Item: LIGHT_GRAY_WOOL
  Gray:
    Colour: "#818181"
    Item: STONE
  Black:
    Colour: "#000000"
    Item: BLACK_WOOL

# Group Specific name colours.
# Use the permission `stylizer.namecolour.groups.<group name>`
Group_Name_Colour:
  # Whether or not you want per-group name colours
  Enabled: true
  # The groups and their respective name colour
  Groups:
    owner: '&4'
    admin: '&b'
    
# Group Specific chat colours.
# Use the permission `stylizer.chatcolour.groups.<group chat>`
Group_Chat_Colour:
  # Whether or not you want per-group chat colours
  Enabled: true
  # The groups and their respective chat colour
  Groups:
    owner: '&4'
    admin: '&b'

# Here you are able to stylize how your chat messages look!
# All PlaceholderAPI placeholders can be used!
Chat_Settings:
  # Whether or not you want Stylizer to style the chat.
  Enabled: true
  # Whether you want Stylizer to log all the chat messages.
  Log_Chat_Messages: false
  # This is where you can determine the different formats that players will use in chat messages.
  Chat_Formats:
    # This is the main chat format that all players will have if they don't have one of the group formats below.
    # Spaces will automatically be added after the prefix if you use `%prefix%`
    # Spaces will automatically be added before and after the suffix if you use `%suffix%`
    Default_Format: "%displayname% #14abc9>> #6b6b6b%message%"
    # Settings for the group chat formats.
    Group_Formats:
      # Whether you want Stylizer to handle group chat formats.
      Enabled: true
      # The different group formats that you want to implement.
      # Players will need the permissions `stylizer.chat.groups.<group name>` to use one of the formats below.
      Groups:
        owner: "#6b6b6b&l[#570000STAFF#6b6b6b&l] %prefix%%displayname%%suffix%#ff4a4a>> #14abc9%message%"
        admin: "#6b6b6b&l[#570000STAFF#6b6b6b&l] %prefix%%displayname%%suffix%#14abc9>> #ff4a4a%message%"
        member: "%prefix%%displayname%%suffix% #14abc9>> #6b6b6b%message%"
# Stylize how you would like the tablist to look like
Tablist:
  # Whether or not you want Stylizer to style the tablist.
  Enabled: true
  # The tablist header message
  # Use %player% to get the players name (Prefixes and Suffixes included)
  Tablist_Header:
    - "#14abc9Welcome to the server %player%"
    - "#00D4FFI hope you enjoy your time with us!"
  Tablist_Footer:
    - "#14abc9Please check out our website!"
    - "#14abc9Remember to vote for us!"
  # Determine the order which the tablist will be sorted in
  # Assign the permission `stylizer.tablist.order.<group name>` to the groups
  # The order will go from top to bottom
  Sorting_Order:
    Enabled: true
    Order:
      - owner
      - admin
      - moderator
      - vip
      - default
  # Set the different formats for players in the tablist.
  # Use `%playername%` to get the players name without any colour added.
  # ALL PlaceholderAPI placeholders are accepted.
  Player_Name_Formats:
    # Whether you want to use the custom tablist player names.
    Enabled: true
    # The default format used if a player does not have one of the group formats below.
    Default_Format: "%playername%"
    # The different group formats.
    Group_Formats:
      # Whether you want to use group formats or not.
      Enabled: true
      # The specific group formats.
      # Use the permission `stylizer.tablist.groups.<group name>` to give players access to one of the groups
      # It goes from top to bottom - So the first one it finds if the one it will use.
      Groups:
        owner: "#6b6b6b&l[#570000OWNER#6b6b6b&l] %displayname%"
        staff: "#6b6b6b&l[#570000STAFF#6b6b6b&l] %displayname%"
        player: "%prefix% %displayname%"

# Set the name colour that will be used for the above head names
# Sadly these cannot be hex colours, thus, cannot use the normal name colours set.
Player_Name_Tags:
  # Whether or not you're wanting above head names
  Enabled: true
  # If you're wanting a players prefix to display above their heads.
  Player_Prefixes: true
  Groups:
    owner: "&c"
    moderator: "&b"
    default: "&e"

# Set some special announcement messages that will be broadcast to your whole server.
Announcement_Messages:
  # Whether or not you want Stylizer to use annoucement messages.
  Enabled: true
  # The messages to be broadcast
  # All messages fully support PlaceholderAPI placeholders.
  Messages:
    vote:
      Message: "#fc0356Remember to vote for the server www.ourwebsite.com/vote"
      Hover:
        Enabled: true
        Hover_Message:
          - "#FF4A4AOur Website"
          - "#FF4A4AAll are welcome!"
    website:
      Message: "#90fc03Get a free member rank on our website! www.ourwebsite.com/member"
      Hover:
        Enabled: true
        Hover_Message:
          - "#FF4A4AIf you vote for us, you will"
          - "#FF4A4Aget some amazing shiny new rewards."
          - "#FF4A4ASo what are you waiting for? Vote!"
    discord:
      Message: "#90FC03Join our amazing discord community! discord.gg/fakediscordserver"
      Hover:
        Enabled: true
        Hover_Message:
          - "#FF4A4ACheck out out discord server"
          - "#FF4A4Aand you might get a special"
          - "#FF4A4Arank in-game or some rewards!"
  # The time inbetween each announcement message.
  # The time is in seconds.
  Interval: 300 # default 300 - 5 minutes

# Display a pretty message for your server in the multiplayer server list
Server_Listing:
  # Whether or not you want Stylizer to display a message.
  Enabled: true
  # The message that you want displayed.
  Format:
    - "#14abc9[+] #ff4a4aEveryone is welcome! #14abc9[+]"
    - "#14abc9=[*]= #ff4a4aAn amazing social minecraft server #14abc9=[*]="

# If true, players with the permission `stylizer.update` will receive update messages
Update_Messages: true

# DO NOT EDIT THIS
Config_Version: 2.10