name: ${name}
description: An advanced chat/tablist plugin
version: ${version}
api-version: ${apiVersion}
main: ${mainClass}
author: ${author}

depend:
  - Vault

softdepend:
  - PlaceholderAPI

commands:
  stylizer:
    description: The main command for OmegaNames
    aliases: [styles]
  namecolour:
    description: The name colour command
    aliases: [nc, namec, namecolours, ncolours]
  chatcolour:
    description: The chat colour command
    aliases: [cc, chatc, chatcolours, ccolours]
  stylizerdebug:
    description: Display useful information to help debug issues
    aliases: [styledebug]
  itemnamer:
    description: Edit the name and lore of an item
    aliases: [styleitem, itemstyles, itemname]
  stylizerclearlog:
    description: The clear log command
    aliases: [scl, sclearlog, stylizercl]

permissions:
  stylizer.admin:
    description: Grants the user access to all the main permissions, but not group colours
    default: false
    children:
      - stylizer.reload
      - stylizer.update
      - stylizer.debug
      - stylizer.namecolour.add
      - stylizer.namecolour.remove
      - stylizer.namecolour.colours
      - stylizer.namecolour.colour.all
      - stylizer.namecolour.login
      - stylizer.namecolour.open
      - stylizer.chatcolour.add
      - stylizer.chatcolour.remove
      - stylizer.chatcolour.colours
      - stylizer.chatcolour.colour.all
      - stylizer.chatcolour.login
      - stylizer.chatcolour.open
      - stylizer.itemnamer.admin
      - stylizer.clearlog
  stylizer.reload:
    description: Grants the user access to the reload command
    default: false
  stylizer.update:
    description: Allows the user to recieve the update messages in-game
    default: false
  stylizer.namecolour.open:
    description: Grants the user access to the name colour command
    default: false
  stylizer.namecolour.login:
    description: Allows the user to retain their name colour when they login/logout
    default: false
  stylizer.namecolour.colours:
    description: Allows the user to use all the colours if Per_Name_Colour_Permissions is disabled
    default: false
  stylizer.namecolour.colour.all:
    description: Allows the user to use all the colours if Per_Name_Colour_Permissions is enabled
    default: false
  stylizer.namecolour.add:
    description: Allows the user to use the name colour add command
    default: false
  stylizer.namecolour.remove:
    description: Allows the user to use the name colour remove command
    default: false
  stylizer.debug:
    description: Allows the user to use the debug command
    default: false
  stylizer.itemnamer.admin:
    description: Allows the user to use all the itemnamer commands
    default: false
    children:
      - stylizer.itemnamer.use
      - stylizer.itemnamer.set.name
      - stylizer.itemnamer.set.lore
      - stylizer.itemnamer.remove.name
      - stylizer.itemnamer.remove.lore
  stylizer.itemnamer.use:
    description: Allows the user to use the itemnamer command
    default: false
  stylizer.itemnamer.set.name:
    description: Allows the user to set custom item names
    default: false
  stylizer.itemnamer.set.lore:
    description: Allows the user to set custom item lore
    default: false
  stylizer.itemnamer.remove.name:
    description: Allows the user to remove custom item names
    default: false
  stylizer.itemnamer.remove.lore:
    description: Allows the user to remove custom item lore
    default: false
  stylizer.clearlog:
    description: Allows the user to use the clearlog command
    default: false
  stylizer.chatcolour.add:
    description: Allows the user to use the chat colour add command
    default: false
  stylizer.chatcolour.remove:
    description: Allows the user to use the chat colour remove command
    default: false
  stylizer.chatcolour.colours:
    description: Allows the user to use all the colours if Per_Chat_Colour_Permissions is disabled
    default: false
  stylizer.chatcolour.colour.all:
    description: Allows the user to use all the colours if Per_Chat_Colour_Permissions is enabled
    default: false
  stylizer.chatcolour.login:
    description: Allows the user to retain their chat colour when they login/logout
    default: false
  stylizer.chatcolour.open:
    description: Allows the user to open the chat colour menu
    default: false